### ISSUE TITLE
(Optional) Create a LinkedIn post

### ISSUE THREAD

**Issue by HCA97** [HCA97/Mosquito-Classifiction#36]
Hi @fkemeth, I want to make a LinkedIn post about our results for some PR! 😊 Since this was a group effort, I'd like your permission to share the post. If you're not okay with it, I won't post it.

**Comment by fkemeth** [comment]
Hi @HCA97 , thank you for asking! That is fine with me

**Comment by HCA97** [comment]
Done! @fkemeth 

https://www.linkedin.com/posts/hidir-cem-altun-914aaa65_mosquito-detection-a-hugging-face-space-activity-7129204636325957632-z5Ju?utm_source=share&utm_medium=member_desktop
